### PR TITLE
Soften the requirements

### PR DESCRIPTION
**Pull request by fabaff**
Strict pinning blocks the installation outside of a `venv`. E.g., Fedora already ships `pytest-asyncio-0.10.0`.

### CODE REVIEW

**Comment by Lenka42** [comment]
@fabaff Thanks for this PR, I would prefer to use strictly frozen set of requirements only with `==`, not `>=` Could you provide precise requirements, which work for you?

**Comment by Lenka42** [comment]
Hi, I figured out that we actually use `pytest-asyncio-0.10.0` So I updated test requirements in `setup.py` in PR #84 Please check version `0.5.3`

**Comment by fabaff** [comment]
> Could you provide precise requirements, which work for you?

No, I can't. Fedora Rawhide ships `pytest-4.6.7. Thus the update in #84 doesn't help, especially that 4.5.0 was released over six months ago. Fedora 31 also has 4.6.7. And Fedora 30 `pytest-3.10.1`. If there is `pytest` update tomorrow then it needs to be 4.6.9 (4.6.8 was released 11 days ago) as this is the release that we have in the Fedora development version that will become Fedora 32.

This applies to almost every distribution. Different releases have a different package set.

The pinning makes your life harder (like the mismatch of the requirements that was present in `test_requirements.txt` and `setup.py`) and mine. To get `gmqtt` into Fedora I would have to ship a patch that gets rid of the pinning to make it work with the dependency generator.

Projects try to keep their stuff running and pinning is a way to do it. This works as long as you are in your little bubble but at the end of the day it only works in the world if we (developers, maintainers, and packagers) make little compromises.

**Comment by Lenka42** [comment]
@fabaff how do you install the package? In general gmqtt does not have any dependencies, only running tests require some extra packages. And for this I highly recommend using virtual environment in order not to mess up with system packages.

**Comment by Lenka42** [comment]
@fabaff if you still think test requirements must be softened, could you please make this PR up-to-date with master branch?

**Comment by fabaff** [comment]
> @fabaff how do you install the package? 

Not installing, but creating a package which can be installed.

> In general gmqtt does not have any dependencies, only running tests require some extra packages. 

All pinning is problematic as mentioned already. I can run the tests in the current state on the build system. They are disabled thus it's the workaround.

> And for this I highly recommend using virtual environment in order not to mess up with system packages.

If the package is coming out of the Package repo it's placed along all other modules which allows one to update the system with the distro's package management tools.

**Comment by Lenka42** [comment]
Hi @fabaff I merged `>=` requrements in #90 Check it out

**Pull request closed without merging**
